def menu():
    print("\n" + "=" * 40)
    print("        SISTEMA HOSPITALAR")
    print("=" * 40)
    print("1  - Cadastrar paciente")
    print("2  - Listar pacientes")
    print("3  - Atualizar paciente")
    print("4  - Excluir paciente")
    print("5  - Cadastrar médico")
    print("6  - Listar médicos")
    print("7  - Agendar consulta")
    print("8  - Cancelar consulta")
    print("9  - Listar consultas")
    print("10 - Registrar pagamento")
    print("11 - Consulta: Paciente x Médico")
    print("12 - Faturamento por médico")
    print("13 - Relatório por especialidade")
    print("14 - Relatório consultas e pagamentos")
    print("15 - Ranking de médicos")
    print("16 - Ranking de especialidades")
    print("17 - Numeração das consultas")
    print("18 - Comparação de faturamento dos pacientes")
    print("19 - Relatório pacientes")
    print("0  - Sair")
    print("=" * 40)